version: 0.0
os: windows
files:
  - source: \SoccerTeamWeb\Default.aspx
    destination: c:\inetpub\wwwroot\SoccerTeamWeb
  - source: \SoccerTeamWeb\Web.config
    destination: c:\inetpub\wwwroot\SoccerTeamWeb
  - source: \SoccerTeamWeb\bin\SoccerTeamWeb.dll
    destination: c:\inetpub\wwwroot\SoccerTeamWeb
	- source: \SoccerTeamWeb\bin\deployment\scripts\installwebsite.ps1
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: \SoccerTeamWeb\bin\deployment\scripts\installwebsite.bat
      timeout: 900