version: 0.0
os: windows
files:
  - source: \SoccerTeamWeb\bin\deployment\content\Default.aspx
    destination: c:\inetpub\wwwroot\SoccerTeamWeb
  - source: \SoccerTeamWeb\bin\deployment\content\Web.config
    destination: c:\inetpub\wwwroot\SoccerTeamWeb
  - source: \SoccerTeamWeb\bin\deployment\content\SoccerTeamWeb.dll
    destination: c:\inetpub\wwwroot\SoccerTeamWeb\bin
  - source: \SoccerTeamWeb\bin\deployment\scripts\deletewebsite.ps1
    destination: c:\temp
  - source: \SoccerTeamWeb\bin\deployment\scripts\installwebsite.ps1
    destination: c:\temp
hooks:
  BeforeInstall:
    - location: \SoccerTeamWeb\bin\deployment\scripts\deletewebsite.bat
      timeout: 900
  AfterInstall:
    - location: \SoccerTeamWeb\bin\deployment\scripts\installwebsite.bat
      timeout: 900